//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace LLDB
{
    public unsafe partial class FileSpecList : IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 4)]
        public partial struct Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="??0SBFileSpecList@lldb@@QAE@XZ")]
            internal static extern global::System.IntPtr ctor_0(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="??0SBFileSpecList@lldb@@QAE@ABV01@@Z")]
            internal static extern global::System.IntPtr cctor_1(global::System.IntPtr instance, global::System.IntPtr rhs);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="??1SBFileSpecList@lldb@@QAE@XZ")]
            internal static extern void dtor_0(global::System.IntPtr instance, int delete);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?GetDescription@SBFileSpecList@lldb@@QBE_NAAVSBStream@2@@Z")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool GetDescription_0(global::System.IntPtr instance, global::System.IntPtr description);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?Append@SBFileSpecList@lldb@@QAEXABVSBFileSpec@2@@Z")]
            internal static extern void Append_0(global::System.IntPtr instance, global::System.IntPtr sb_file);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?AppendIfUnique@SBFileSpecList@lldb@@QAE_NABVSBFileSpec@2@@Z")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool AppendIfUnique_0(global::System.IntPtr instance, global::System.IntPtr sb_file);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?Clear@SBFileSpecList@lldb@@QAEXXZ")]
            internal static extern void Clear_0(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?FindFileIndex@SBFileSpecList@lldb@@QAEIIABVSBFileSpec@2@_N@Z")]
            internal static extern uint FindFileIndex_0(global::System.IntPtr instance, uint idx, global::System.IntPtr sb_file, bool full);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?GetFileSpecAtIndex@SBFileSpecList@lldb@@QBE?BVSBFileSpec@2@I@Z")]
            internal static extern void GetFileSpecAtIndex_0(global::System.IntPtr instance, global::System.IntPtr @return, uint idx);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?GetSize@SBFileSpecList@lldb@@QBEIXZ")]
            internal static extern uint GetSize_0(global::System.IntPtr instance);
        }

        public global::System.IntPtr __Instance { get; protected set; }
        public static readonly System.Collections.Concurrent.ConcurrentDictionary<IntPtr, FileSpecList> NativeToManagedMap = new System.Collections.Concurrent.ConcurrentDictionary<IntPtr, FileSpecList>();

        private readonly bool __ownsNativeInstance;

        public static FileSpecList __CreateInstance(global::System.IntPtr native)
        {
            return new FileSpecList((FileSpecList.Internal*) native);
        }

        public static FileSpecList __CreateInstance(FileSpecList.Internal native)
        {
            return new FileSpecList(native);
        }

        private static FileSpecList.Internal* __CopyValue(FileSpecList.Internal native)
        {
            var ret = (FileSpecList.Internal*) Marshal.AllocHGlobal(4);
            *ret = native;
            return ret;
        }

        private FileSpecList(FileSpecList.Internal native)
            : this(__CopyValue(native))
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected FileSpecList(FileSpecList.Internal* native, bool isInternalImpl = false)
        {
            __Instance = new global::System.IntPtr(native);
        }

        public FileSpecList()
        {
            __Instance = Marshal.AllocHGlobal(4);
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            Internal.ctor_0(__Instance);
        }

        public void Dispose()
        {
            Dispose(disposing: true);
        }

        protected virtual void Dispose(bool disposing)
        {
            DestroyNativeInstance(false);
        }

        public virtual void DestroyNativeInstance()
        {
            DestroyNativeInstance(true);
        }

        private void DestroyNativeInstance(bool force)
        {
            LLDB.FileSpecList __dummy;
            NativeToManagedMap.TryRemove(__Instance, out __dummy);
            if (__ownsNativeInstance || force)
                Internal.dtor_0(__Instance, 0);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
        }

        public bool GetDescription(LLDB.Stream description)
        {
            var arg0 = ReferenceEquals(description, null) ? global::System.IntPtr.Zero : description.__Instance;
            var __ret = Internal.GetDescription_0(__Instance, arg0);
            return __ret;
        }

        public void Append(LLDB.FileSpec sb_file)
        {
            var arg0 = ReferenceEquals(sb_file, null) ? global::System.IntPtr.Zero : sb_file.__Instance;
            Internal.Append_0(__Instance, arg0);
        }

        public bool AppendIfUnique(LLDB.FileSpec sb_file)
        {
            var arg0 = ReferenceEquals(sb_file, null) ? global::System.IntPtr.Zero : sb_file.__Instance;
            var __ret = Internal.AppendIfUnique_0(__Instance, arg0);
            return __ret;
        }

        public void Clear()
        {
            Internal.Clear_0(__Instance);
        }

        public uint FindFileIndex(uint idx, LLDB.FileSpec sb_file, bool full)
        {
            var arg0 = idx;
            var arg1 = ReferenceEquals(sb_file, null) ? global::System.IntPtr.Zero : sb_file.__Instance;
            var __ret = Internal.FindFileIndex_0(__Instance, arg0, arg1, full);
            return __ret;
        }

        public LLDB.FileSpec GetFileSpecAtIndex(uint idx)
        {
            var arg0 = idx;
            var __ret = new LLDB.FileSpec.Internal();
            Internal.GetFileSpecAtIndex_0(__Instance, new IntPtr(&__ret), arg0);
            return LLDB.FileSpec.__CreateInstance(__ret);
        }

        public uint Size
        {
            get
            {
                var __ret = Internal.GetSize_0(__Instance);
                return __ret;
            }
        }
    }
}
