//----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace LLDB
{
    public unsafe partial class Listener : IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 12)]
        public partial struct Internal
        {
            [FieldOffset(8)]
            public global::System.IntPtr m_unused_ptr;

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="??0SBListener@lldb@@QAE@XZ")]
            internal static extern global::System.IntPtr ctor_0(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="??0SBListener@lldb@@QAE@PBD@Z")]
            internal static extern global::System.IntPtr ctor_1(global::System.IntPtr instance, global::System.IntPtr name);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="??0SBListener@lldb@@QAE@ABV01@@Z")]
            internal static extern global::System.IntPtr cctor_2(global::System.IntPtr instance, global::System.IntPtr rhs);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="??1SBListener@lldb@@QAE@XZ")]
            internal static extern void dtor_0(global::System.IntPtr instance, int delete);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?AddEvent@SBListener@lldb@@QAEXABVSBEvent@2@@Z")]
            internal static extern void AddEvent_0(global::System.IntPtr instance, global::System.IntPtr @event);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?Clear@SBListener@lldb@@QAEXXZ")]
            internal static extern void Clear_0(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?IsValid@SBListener@lldb@@QBE_NXZ")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool IsValid_0(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?StartListeningForEventClass@SBListener@lldb@@QAEIAAVSBDebugger@2@PBDI@Z")]
            internal static extern uint StartListeningForEventClass_0(global::System.IntPtr instance, global::System.IntPtr debugger, global::System.IntPtr broadcaster_class, uint event_mask);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?StopListeningForEventClass@SBListener@lldb@@QAE_NAAVSBDebugger@2@PBDI@Z")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool StopListeningForEventClass_0(global::System.IntPtr instance, global::System.IntPtr debugger, global::System.IntPtr broadcaster_class, uint event_mask);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?StartListeningForEvents@SBListener@lldb@@QAEIABVSBBroadcaster@2@I@Z")]
            internal static extern uint StartListeningForEvents_0(global::System.IntPtr instance, global::System.IntPtr broadcaster, uint event_mask);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?StopListeningForEvents@SBListener@lldb@@QAE_NABVSBBroadcaster@2@I@Z")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool StopListeningForEvents_0(global::System.IntPtr instance, global::System.IntPtr broadcaster, uint event_mask);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?WaitForEvent@SBListener@lldb@@QAE_NIAAVSBEvent@2@@Z")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool WaitForEvent_0(global::System.IntPtr instance, uint num_seconds, global::System.IntPtr @event);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?WaitForEventForBroadcaster@SBListener@lldb@@QAE_NIABVSBBroadcaster@2@AAVSBEvent@2@@Z")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool WaitForEventForBroadcaster_0(global::System.IntPtr instance, uint num_seconds, global::System.IntPtr broadcaster, global::System.IntPtr sb_event);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?WaitForEventForBroadcasterWithType@SBListener@lldb@@QAE_NIABVSBBroadcaster@2@IAAVSBEvent@2@@Z")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool WaitForEventForBroadcasterWithType_0(global::System.IntPtr instance, uint num_seconds, global::System.IntPtr broadcaster, uint event_type_mask, global::System.IntPtr sb_event);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?PeekAtNextEvent@SBListener@lldb@@QAE_NAAVSBEvent@2@@Z")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool PeekAtNextEvent_0(global::System.IntPtr instance, global::System.IntPtr sb_event);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?PeekAtNextEventForBroadcaster@SBListener@lldb@@QAE_NABVSBBroadcaster@2@AAVSBEvent@2@@Z")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool PeekAtNextEventForBroadcaster_0(global::System.IntPtr instance, global::System.IntPtr broadcaster, global::System.IntPtr sb_event);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?PeekAtNextEventForBroadcasterWithType@SBListener@lldb@@QAE_NABVSBBroadcaster@2@IAAVSBEvent@2@@Z")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool PeekAtNextEventForBroadcasterWithType_0(global::System.IntPtr instance, global::System.IntPtr broadcaster, uint event_type_mask, global::System.IntPtr sb_event);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?GetNextEvent@SBListener@lldb@@QAE_NAAVSBEvent@2@@Z")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool GetNextEvent_0(global::System.IntPtr instance, global::System.IntPtr sb_event);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?GetNextEventForBroadcaster@SBListener@lldb@@QAE_NABVSBBroadcaster@2@AAVSBEvent@2@@Z")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool GetNextEventForBroadcaster_0(global::System.IntPtr instance, global::System.IntPtr broadcaster, global::System.IntPtr sb_event);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?GetNextEventForBroadcasterWithType@SBListener@lldb@@QAE_NABVSBBroadcaster@2@IAAVSBEvent@2@@Z")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool GetNextEventForBroadcasterWithType_0(global::System.IntPtr instance, global::System.IntPtr broadcaster, uint event_type_mask, global::System.IntPtr sb_event);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint="?HandleBroadcastEvent@SBListener@lldb@@QAE_NABVSBEvent@2@@Z")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool HandleBroadcastEvent_0(global::System.IntPtr instance, global::System.IntPtr @event);
        }

        public global::System.IntPtr __Instance { get; protected set; }

        protected int __PointerAdjustment;
        public static readonly System.Collections.Concurrent.ConcurrentDictionary<IntPtr, Listener> NativeToManagedMap = new System.Collections.Concurrent.ConcurrentDictionary<IntPtr, Listener>();
        protected void*[] __OriginalVTables;

        protected bool __ownsNativeInstance;

        public static Listener __CreateInstance(global::System.IntPtr native, bool skipVTables = false)
        {
            return new Listener(native.ToPointer(), skipVTables);
        }

        public static Listener __CreateInstance(Listener.Internal native, bool skipVTables = false)
        {
            return new Listener(native, skipVTables);
        }

        private static void* __CopyValue(Listener.Internal native)
        {
            var ret = Marshal.AllocHGlobal(12);
            LLDB.Listener.Internal.cctor_2(ret, new global::System.IntPtr(&native));
            return ret.ToPointer();
        }

        private Listener(Listener.Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected Listener(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new global::System.IntPtr(native);
        }

        public Listener()
        {
            __Instance = Marshal.AllocHGlobal(12);
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            Internal.ctor_0((__Instance + __PointerAdjustment));
        }

        public Listener(string name)
        {
            __Instance = Marshal.AllocHGlobal(12);
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            var arg0 = Marshal.StringToHGlobalAnsi(name);
            Internal.ctor_1((__Instance + __PointerAdjustment), arg0);
            Marshal.FreeHGlobal(arg0);
        }

        public Listener(LLDB.Listener rhs)
        {
            __Instance = Marshal.AllocHGlobal(12);
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            if (ReferenceEquals(rhs, null))
                throw new global::System.ArgumentNullException("rhs", "Cannot be null because it is a C++ reference (&).");
            var arg0 = rhs.__Instance;
            Internal.cctor_2((__Instance + __PointerAdjustment), arg0);
        }

        public void Dispose()
        {
            Dispose(disposing: true);
        }

        protected virtual void Dispose(bool disposing)
        {
            LLDB.Listener __dummy;
            NativeToManagedMap.TryRemove(__Instance, out __dummy);
            Internal.dtor_0((__Instance + __PointerAdjustment), 0);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
        }

        public void AddEvent(LLDB.Event @event)
        {
            if (ReferenceEquals(@event, null))
                throw new global::System.ArgumentNullException("@event", "Cannot be null because it is a C++ reference (&).");
            var arg0 = @event.__Instance;
            Internal.AddEvent_0((__Instance + __PointerAdjustment), arg0);
        }

        public void Clear()
        {
            Internal.Clear_0((__Instance + __PointerAdjustment));
        }

        public bool IsValid()
        {
            var __ret = Internal.IsValid_0((__Instance + __PointerAdjustment));
            return __ret;
        }

        public uint StartListeningForEventClass(LLDB.Debugger debugger, string broadcaster_class, uint event_mask)
        {
            if (ReferenceEquals(debugger, null))
                throw new global::System.ArgumentNullException("debugger", "Cannot be null because it is a C++ reference (&).");
            var arg0 = debugger.__Instance;
            var arg1 = Marshal.StringToHGlobalAnsi(broadcaster_class);
            var __ret = Internal.StartListeningForEventClass_0((__Instance + __PointerAdjustment), arg0, arg1, event_mask);
            Marshal.FreeHGlobal(arg1);
            return __ret;
        }

        public bool StopListeningForEventClass(LLDB.Debugger debugger, string broadcaster_class, uint event_mask)
        {
            if (ReferenceEquals(debugger, null))
                throw new global::System.ArgumentNullException("debugger", "Cannot be null because it is a C++ reference (&).");
            var arg0 = debugger.__Instance;
            var arg1 = Marshal.StringToHGlobalAnsi(broadcaster_class);
            var __ret = Internal.StopListeningForEventClass_0((__Instance + __PointerAdjustment), arg0, arg1, event_mask);
            Marshal.FreeHGlobal(arg1);
            return __ret;
        }

        public uint StartListeningForEvents(LLDB.Broadcaster broadcaster, uint event_mask)
        {
            if (ReferenceEquals(broadcaster, null))
                throw new global::System.ArgumentNullException("broadcaster", "Cannot be null because it is a C++ reference (&).");
            var arg0 = broadcaster.__Instance;
            var __ret = Internal.StartListeningForEvents_0((__Instance + __PointerAdjustment), arg0, event_mask);
            return __ret;
        }

        public bool StopListeningForEvents(LLDB.Broadcaster broadcaster, uint event_mask)
        {
            if (ReferenceEquals(broadcaster, null))
                throw new global::System.ArgumentNullException("broadcaster", "Cannot be null because it is a C++ reference (&).");
            var arg0 = broadcaster.__Instance;
            var __ret = Internal.StopListeningForEvents_0((__Instance + __PointerAdjustment), arg0, event_mask);
            return __ret;
        }

        public bool WaitForEvent(uint num_seconds, LLDB.Event @event)
        {
            if (ReferenceEquals(@event, null))
                throw new global::System.ArgumentNullException("@event", "Cannot be null because it is a C++ reference (&).");
            var arg1 = @event.__Instance;
            var __ret = Internal.WaitForEvent_0((__Instance + __PointerAdjustment), num_seconds, arg1);
            return __ret;
        }

        public bool WaitForEventForBroadcaster(uint num_seconds, LLDB.Broadcaster broadcaster, LLDB.Event sb_event)
        {
            if (ReferenceEquals(broadcaster, null))
                throw new global::System.ArgumentNullException("broadcaster", "Cannot be null because it is a C++ reference (&).");
            var arg1 = broadcaster.__Instance;
            if (ReferenceEquals(sb_event, null))
                throw new global::System.ArgumentNullException("sb_event", "Cannot be null because it is a C++ reference (&).");
            var arg2 = sb_event.__Instance;
            var __ret = Internal.WaitForEventForBroadcaster_0((__Instance + __PointerAdjustment), num_seconds, arg1, arg2);
            return __ret;
        }

        public bool WaitForEventForBroadcasterWithType(uint num_seconds, LLDB.Broadcaster broadcaster, uint event_type_mask, LLDB.Event sb_event)
        {
            if (ReferenceEquals(broadcaster, null))
                throw new global::System.ArgumentNullException("broadcaster", "Cannot be null because it is a C++ reference (&).");
            var arg1 = broadcaster.__Instance;
            if (ReferenceEquals(sb_event, null))
                throw new global::System.ArgumentNullException("sb_event", "Cannot be null because it is a C++ reference (&).");
            var arg3 = sb_event.__Instance;
            var __ret = Internal.WaitForEventForBroadcasterWithType_0((__Instance + __PointerAdjustment), num_seconds, arg1, event_type_mask, arg3);
            return __ret;
        }

        public bool PeekAtNextEvent(LLDB.Event sb_event)
        {
            if (ReferenceEquals(sb_event, null))
                throw new global::System.ArgumentNullException("sb_event", "Cannot be null because it is a C++ reference (&).");
            var arg0 = sb_event.__Instance;
            var __ret = Internal.PeekAtNextEvent_0((__Instance + __PointerAdjustment), arg0);
            return __ret;
        }

        public bool PeekAtNextEventForBroadcaster(LLDB.Broadcaster broadcaster, LLDB.Event sb_event)
        {
            if (ReferenceEquals(broadcaster, null))
                throw new global::System.ArgumentNullException("broadcaster", "Cannot be null because it is a C++ reference (&).");
            var arg0 = broadcaster.__Instance;
            if (ReferenceEquals(sb_event, null))
                throw new global::System.ArgumentNullException("sb_event", "Cannot be null because it is a C++ reference (&).");
            var arg1 = sb_event.__Instance;
            var __ret = Internal.PeekAtNextEventForBroadcaster_0((__Instance + __PointerAdjustment), arg0, arg1);
            return __ret;
        }

        public bool PeekAtNextEventForBroadcasterWithType(LLDB.Broadcaster broadcaster, uint event_type_mask, LLDB.Event sb_event)
        {
            if (ReferenceEquals(broadcaster, null))
                throw new global::System.ArgumentNullException("broadcaster", "Cannot be null because it is a C++ reference (&).");
            var arg0 = broadcaster.__Instance;
            if (ReferenceEquals(sb_event, null))
                throw new global::System.ArgumentNullException("sb_event", "Cannot be null because it is a C++ reference (&).");
            var arg2 = sb_event.__Instance;
            var __ret = Internal.PeekAtNextEventForBroadcasterWithType_0((__Instance + __PointerAdjustment), arg0, event_type_mask, arg2);
            return __ret;
        }

        public bool GetNextEvent(LLDB.Event sb_event)
        {
            if (ReferenceEquals(sb_event, null))
                throw new global::System.ArgumentNullException("sb_event", "Cannot be null because it is a C++ reference (&).");
            var arg0 = sb_event.__Instance;
            var __ret = Internal.GetNextEvent_0((__Instance + __PointerAdjustment), arg0);
            return __ret;
        }

        public bool GetNextEventForBroadcaster(LLDB.Broadcaster broadcaster, LLDB.Event sb_event)
        {
            if (ReferenceEquals(broadcaster, null))
                throw new global::System.ArgumentNullException("broadcaster", "Cannot be null because it is a C++ reference (&).");
            var arg0 = broadcaster.__Instance;
            if (ReferenceEquals(sb_event, null))
                throw new global::System.ArgumentNullException("sb_event", "Cannot be null because it is a C++ reference (&).");
            var arg1 = sb_event.__Instance;
            var __ret = Internal.GetNextEventForBroadcaster_0((__Instance + __PointerAdjustment), arg0, arg1);
            return __ret;
        }

        public bool GetNextEventForBroadcasterWithType(LLDB.Broadcaster broadcaster, uint event_type_mask, LLDB.Event sb_event)
        {
            if (ReferenceEquals(broadcaster, null))
                throw new global::System.ArgumentNullException("broadcaster", "Cannot be null because it is a C++ reference (&).");
            var arg0 = broadcaster.__Instance;
            if (ReferenceEquals(sb_event, null))
                throw new global::System.ArgumentNullException("sb_event", "Cannot be null because it is a C++ reference (&).");
            var arg2 = sb_event.__Instance;
            var __ret = Internal.GetNextEventForBroadcasterWithType_0((__Instance + __PointerAdjustment), arg0, event_type_mask, arg2);
            return __ret;
        }

        public bool HandleBroadcastEvent(LLDB.Event @event)
        {
            if (ReferenceEquals(@event, null))
                throw new global::System.ArgumentNullException("@event", "Cannot be null because it is a C++ reference (&).");
            var arg0 = @event.__Instance;
            var __ret = Internal.HandleBroadcastEvent_0((__Instance + __PointerAdjustment), arg0);
            return __ret;
        }
    }
}
