//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace LLDB
{
    public enum StateType : uint
    {
        Invalid = 0,
        /// <summary>Process is object is valid, but not currently loaded</summary>
        Unloaded = 1,
        /// <summary>Process is connected to remote debug services, but not launched or attached to anything yet</summary>
        Connected = 2,
        /// <summary>Process is currently trying to attach</summary>
        Attaching = 3,
        /// <summary>Process is in the process of launching</summary>
        Launching = 4,
        /// <summary>Process or thread is stopped and can be examined.</summary>
        Stopped = 5,
        /// <summary>Process or thread is running and can't be examined.</summary>
        Running = 6,
        /// <summary>Process or thread is in the process of stepping and can not be examined.</summary>
        Stepping = 7,
        /// <summary>Process or thread has crashed and can be examined.</summary>
        Crashed = 8,
        /// <summary>Process has been detached and can't be examined.</summary>
        Detached = 9,
        /// <summary>Process has exited and can't be examined.</summary>
        Exited = 10,
        /// <summary>Process or thread is in a suspended state as far as the debugger is concerned while other processes or threads get the chance to run.</summary>
        Suspended = 11
    }

    [Flags]
    public enum LaunchFlags : uint
    {
        None = 0,
        /// <summary>Exec when launching and turn the calling process into a new process</summary>
        Exec = 1,
        /// <summary>Stop as soon as the process launches to allow the process to be debugged</summary>
        Debug = 2,
        /// <summary>Stop at the program entry point instead of auto-continuing when launching or attaching at entry point</summary>
        StopAtEntry = 4,
        /// <summary>Disable Address Space Layout Randomization</summary>
        DisableASLR = 8,
        /// <summary>Disable stdio for inferior process (e.g. for a GUI app)</summary>
        DisableSTDIO = 16,
        /// <summary>Launch the process in a new TTY if supported by the host</summary>
        LaunchInTTY = 32,
        /// <summary>Launch the process inside a shell to get shell expansion</summary>
        LaunchInShell = 64,
        /// <summary>Launch the process in a separate process group</summary>
        LaunchInSeparateProcessGroup = 128,
        /// <summary>If you are going to hand the process off (e.g. to debugserver) set this flag so lldb & the handee don't race to set its exit status.</summary>
        DontSetExitStatus = 256,
        /// <summary>If set, then the client stub should detach rather than killing the debugee if it loses connection with lldb.</summary>
        DetachOnError = 512,
        /// <summary>Perform shell-style argument expansion</summary>
        ShellExpandArguments = 1024,
        /// <summary>Close the open TTY on exit</summary>
        CloseTTYOnExit = 2048
    }

    public enum RunMode : uint
    {
        OnlyThisThread = 0,
        AllThreads = 1,
        OnlyDuringStepping = 2
    }

    [Flags]
    public enum ByteOrder : uint
    {
        Invalid = 0,
        Big = 1,
        PDP = 2,
        Little = 4
    }

    public enum Encoding : uint
    {
        Invalid = 0,
        Uint = 1,
        Sint = 2,
        IEEE754 = 3,
        Vector = 4
    }

    public enum Format : uint
    {
        Default = 0,
        Invalid = 0,
        Boolean = 1,
        Binary = 2,
        Bytes = 3,
        BytesWithASCII = 4,
        Char = 5,
        CharPrintable = 6,
        Complex = 7,
        ComplexFloat = 7,
        CString = 8,
        Decimal = 9,
        Enum = 10,
        Hex = 11,
        HexUppercase = 12,
        Float = 13,
        Octal = 14,
        OSType = 15,
        Unicode16 = 16,
        Unicode32 = 17,
        Unsigned = 18,
        Pointer = 19,
        VectorOfChar = 20,
        VectorOfSInt8 = 21,
        VectorOfUInt8 = 22,
        VectorOfSInt16 = 23,
        VectorOfUInt16 = 24,
        VectorOfSInt32 = 25,
        VectorOfUInt32 = 26,
        VectorOfSInt64 = 27,
        VectorOfUInt64 = 28,
        VectorOfFloat16 = 29,
        VectorOfFloat32 = 30,
        VectorOfFloat64 = 31,
        VectorOfUInt128 = 32,
        ComplexInteger = 33,
        CharArray = 34,
        AddressInfo = 35,
        HexFloat = 36,
        Instruction = 37,
        Void = 38,
        mats = 39
    }

    public enum DescriptionLevel : uint
    {
        Brief = 0,
        Full = 1,
        Verbose = 2,
        Initial = 3,
        vels = 4
    }

    public enum ScriptLanguage : uint
    {
        None = 0,
        Python = 1,
        Default = 1
    }

    public enum RegisterKind : uint
    {
        EHFrame = 0,
        DWARF = 1,
        Generic = 2,
        ProcessPlugin = 3,
        LLDB = 4,
        inds = 5
    }

    public enum StopReason : uint
    {
        Invalid = 0,
        None = 1,
        Trace = 2,
        Breakpoint = 3,
        Watchpoint = 4,
        Signal = 5,
        Exception = 6,
        Exec = 7,
        PlanComplete = 8,
        ThreadExiting = 9,
        Instrumentation = 10
    }

    public enum ReturnStatus : uint
    {
        Invalid = 0,
        SuccessFinishNoResult = 1,
        SuccessFinishResult = 2,
        SuccessContinuingNoResult = 3,
        SuccessContinuingResult = 4,
        Started = 5,
        Failed = 6,
        Quit = 7
    }

    public enum ExpressionResults : uint
    {
        Completed = 0,
        SetupError = 1,
        ParseError = 2,
        Discarded = 3,
        Interrupted = 4,
        HitBreakpoint = 5,
        TimedOut = 6,
        ResultUnavailable = 7,
        StoppedForDebug = 8
    }

    public enum ConnectionStatus : uint
    {
        Success = 0,
        EndOfFile = 1,
        Error = 2,
        TimedOut = 3,
        NoConnection = 4,
        LostConnection = 5,
        Interrupted = 6
    }

    public enum ErrorType : uint
    {
        Invalid = 0,
        /// <summary>Generic errors that can be any value.</summary>
        Generic = 1,
        /// <summary>Mach kernel error codes.</summary>
        MachKernel = 2,
        /// <summary>POSIX error codes.</summary>
        POSIX = 3,
        /// <summary>These are from the ExpressionResults enum.</summary>
        Expression = 4,
        /// <summary>Standard Win32 error codes.</summary>
        Win32 = 5
    }

    public enum ValueType : uint
    {
        Invalid = 0,
        VariableGlobal = 1,
        VariableStatic = 2,
        VariableArgument = 3,
        VariableLocal = 4,
        Register = 5,
        RegisterSet = 6,
        ConstResult = 7
    }

    public enum InputReaderGranularity : uint
    {
        Invalid = 0,
        Byte = 1,
        Word = 2,
        Line = 3,
        All = 4
    }

    /// <summary>
    /// <para>These mask bits allow a common interface for queries that can</para>
    /// </summary>
    /// <remarks>
    /// <para>limit the amount of information that gets parsed to only the</para>
    /// <para>information that is requested. These bits also can indicate what</para>
    /// <para>actually did get resolved during query function calls.</para>
    /// <para>Each definition corresponds to a one of the member variables</para>
    /// <para>in this class, and requests that that item be resolved, or</para>
    /// <para>indicates that the member did get resolved.</para>
    /// </remarks>
    public enum SymbolContextItem : uint
    {
        /// <summary>Set when target is requested from a query, or was located in query results</summary>
        Target = 1,
        /// <summary>Set when module is requested from a query, or was located in query results</summary>
        Module = 2,
        /// <summary>Set when comp_unit is requested from a query, or was located in query results</summary>
        CompUnit = 4,
        /// <summary>Set when function is requested from a query, or was located in query results</summary>
        Function = 8,
        /// <summary>Set when the deepest block is requested from a query, or was located in query results</summary>
        Block = 16,
        /// <summary>Set when line_entry is requested from a query, or was located in query results</summary>
        LineEntry = 32,
        /// <summary>Set when symbol is requested from a query, or was located in query results</summary>
        Symbol = 64,
        /// <summary>Indicates to try and lookup everything up during a routine symbol context query.</summary>
        Everything = 127,
        /// <summary>Set when global or static variable is requested from a query, or was located in query results. eSymbolContextVariable is potentially expensive to lookup so it isn't included in eSymbolContextEverything which stops it from being used during frame PC lookups and many other potential address to symbol context lookups.</summary>
        Variable = 128
    }

    [Flags]
    public enum Permissions : uint
    {
        Writable = 1,
        Readable = 2,
        Executable = 4
    }

    public enum InputReaderAction : uint
    {
        Activate = 0,
        AsynchronousOutputWritten = 1,
        Reactivate = 2,
        Deactivate = 3,
        GotToken = 4,
        Interrupt = 5,
        EndOfFile = 6,
        Done = 7
    }

    [Flags]
    public enum BreakpointEventType : uint
    {
        InvalidType = 1,
        Added = 2,
        Removed = 4,
        LocationsAdded = 8,
        LocationsRemoved = 16,
        LocationsResolved = 32,
        Enabled = 64,
        Disabled = 128,
        CommandChanged = 256,
        ConditionChanged = 512,
        IgnoreChanged = 1024,
        ThreadChanged = 2048
    }

    [Flags]
    public enum WatchpointEventType : uint
    {
        InvalidType = 1,
        Added = 2,
        Removed = 4,
        Enabled = 64,
        Disabled = 128,
        CommandChanged = 256,
        ConditionChanged = 512,
        IgnoreChanged = 1024,
        ThreadChanged = 2048,
        TypeChanged = 4096
    }

    /// <summary>
    /// <para>Programming language type.</para>
    /// </summary>
    /// <remarks>
    /// <para>These enumerations use the same language enumerations as the DWARF</para>
    /// <para>specification for ease of use and consistency.</para>
    /// <para>The enum -&gt; string code is in LanguageRuntime.cpp, don't change this</para>
    /// <para>table without updating that code as well.</para>
    /// </remarks>
    public enum LanguageType : uint
    {
        /// <summary>Unknown or invalid language value.</summary>
        Unknown = 0x0,
        /// <summary>ISO C:1989.</summary>
        C89 = 0x1,
        /// <summary>Non-standardized C, such as K&R.</summary>
        C = 0x2,
        /// <summary>ISO Ada:1983.</summary>
        Ada83 = 0x3,
        /// <summary>ISO C++:1998.</summary>
        C_plus_plus = 0x4,
        /// <summary>ISO Cobol:1974.</summary>
        Cobol74 = 0x5,
        /// <summary>ISO Cobol:1985.</summary>
        Cobol85 = 0x6,
        /// <summary>ISO Fortran 77.</summary>
        Fortran77 = 0x7,
        /// <summary>ISO Fortran 90.</summary>
        Fortran90 = 0x8,
        /// <summary>ISO Pascal:1983.</summary>
        Pascal83 = 0x9,
        /// <summary>ISO Modula-2:1996.</summary>
        Modula2 = 0xa,
        /// <summary>Java.</summary>
        Java = 0xb,
        /// <summary>ISO C:1999.</summary>
        C99 = 0xc,
        /// <summary>ISO Ada:1995.</summary>
        Ada95 = 0xd,
        /// <summary>ISO Fortran 95.</summary>
        Fortran95 = 0xe,
        /// <summary>ANSI PL/I:1976.</summary>
        PLI = 0xf,
        /// <summary>Objective-C.</summary>
        ObjC = 0x10,
        /// <summary>Objective-C++.</summary>
        ObjC_plus_plus = 0x11,
        /// <summary>Unified Parallel C.</summary>
        UPC = 0x12,
        /// <summary>D.</summary>
        D = 0x13,
        /// <summary>Python.</summary>
        Python = 0x14,
        /// <summary>OpenCL.</summary>
        OpenCL = 0x15,
        /// <summary>Go.</summary>
        Go = 0x16,
        /// <summary>Modula 3.</summary>
        Modula3 = 0x17,
        /// <summary>Haskell.</summary>
        Haskell = 0x18,
        /// <summary>ISO C++:2003.</summary>
        C_plus_plus_03 = 0x19,
        /// <summary>ISO C++:2011.</summary>
        C_plus_plus_11 = 0x1a,
        /// <summary>OCaml.</summary>
        OCaml = 0x1b,
        /// <summary>Rust.</summary>
        Rust = 0x1c,
        /// <summary>ISO C:2011.</summary>
        C11 = 0x1d,
        /// <summary>Swift.</summary>
        Swift = 0x1e,
        /// <summary>Julia.</summary>
        Julia = 0x1f,
        /// <summary>Dylan.</summary>
        Dylan = 0x20,
        /// <summary>ISO C++:2014.</summary>
        C_plus_plus_14 = 0x21,
        /// <summary>ISO Fortran 2003.</summary>
        Fortran03 = 0x22,
        /// <summary>ISO Fortran 2008.</summary>
        Fortran08 = 0x23,
        /// <summary>Mips_Assembler.</summary>
        MipsAssembler = 0x24,
        /// <summary>RenderScript.</summary>
        ExtRenderScript = 0x25,
        ypes = 38
    }

    public enum InstrumentationRuntimeType : uint
    {
        AddressSanitizer = 0x0,
        ThreadSanitizer = 0x1,
        ypes = 2
    }

    public enum DynamicValueType : uint
    {
        NoDynamicValues = 0,
        DynamicCanRunTarget = 1,
        DynamicDontRunTarget = 2
    }

    public enum AccessType : uint
    {
        None = 0,
        Public = 1,
        Private = 2,
        Protected = 3,
        Package = 4
    }

    public enum CommandArgumentType : uint
    {
        Address = 0,
        AddressOrExpression = 1,
        AliasName = 2,
        AliasOptions = 3,
        Architecture = 4,
        Boolean = 5,
        BreakpointID = 6,
        BreakpointIDRange = 7,
        BreakpointName = 8,
        ByteSize = 9,
        ClassName = 10,
        CommandName = 11,
        Count = 12,
        DescriptionVerbosity = 13,
        DirectoryName = 14,
        DisassemblyFlavor = 15,
        EndAddress = 16,
        Expression = 17,
        ExpressionPath = 18,
        ExprFormat = 19,
        Filename = 20,
        Format = 21,
        FrameIndex = 22,
        FullName = 23,
        FunctionName = 24,
        FunctionOrSymbol = 25,
        GDBFormat = 26,
        HelpText = 27,
        Index = 28,
        Language = 29,
        LineNum = 30,
        LogCategory = 31,
        LogChannel = 32,
        Method = 33,
        Name = 34,
        NewPathPrefix = 35,
        NumLines = 36,
        NumberPerLine = 37,
        Offset = 38,
        OldPathPrefix = 39,
        OneLiner = 40,
        Path = 41,
        PermissionsNumber = 42,
        PermissionsString = 43,
        Pid = 44,
        Plugin = 45,
        ProcessName = 46,
        PythonClass = 47,
        PythonFunction = 48,
        PythonScript = 49,
        QueueName = 50,
        RegisterName = 51,
        RegularExpression = 52,
        RunArgs = 53,
        RunMode = 54,
        ScriptedCommandSynchronicity = 55,
        ScriptLang = 56,
        SearchWord = 57,
        Selector = 58,
        SettingIndex = 59,
        SettingKey = 60,
        SettingPrefix = 61,
        SettingVariableName = 62,
        ShlibName = 63,
        SourceFile = 64,
        SortOrder = 65,
        StartAddress = 66,
        SummaryString = 67,
        Symbol = 68,
        ThreadID = 69,
        ThreadIndex = 70,
        ThreadName = 71,
        TypeName = 72,
        UnsignedInteger = 73,
        UnixSignal = 74,
        VarName = 75,
        Value = 76,
        Width = 77,
        None = 78,
        Platform = 79,
        WatchpointID = 80,
        WatchpointIDRange = 81,
        WatchType = 82,
        LastArg = 83
    }

    public enum SymbolType : uint
    {
        Any = 0,
        Invalid = 0,
        Absolute = 1,
        Code = 2,
        Resolver = 3,
        Data = 4,
        Trampoline = 5,
        Runtime = 6,
        Exception = 7,
        SourceFile = 8,
        HeaderFile = 9,
        ObjectFile = 10,
        CommonBlock = 11,
        Block = 12,
        Local = 13,
        Param = 14,
        Variable = 15,
        VariableType = 16,
        LineEntry = 17,
        LineHeader = 18,
        ScopeBegin = 19,
        ScopeEnd = 20,
        Additional = 21,
        Compiler = 22,
        Instrumentation = 23,
        Undefined = 24,
        ObjCClass = 25,
        ObjCMetaClass = 26,
        ObjCIVar = 27,
        ReExported = 28
    }

    public enum SectionType : uint
    {
        Invalid = 0,
        Code = 1,
        Container = 2,
        Data = 3,
        DataCString = 4,
        DataCStringPointers = 5,
        DataSymbolAddress = 6,
        Data4 = 7,
        Data8 = 8,
        Data16 = 9,
        DataPointers = 10,
        Debug = 11,
        ZeroFill = 12,
        DataObjCMessageRefs = 13,
        DataObjCCFStrings = 14,
        DWARFDebugAbbrev = 15,
        DWARFDebugAddr = 16,
        DWARFDebugAranges = 17,
        DWARFDebugFrame = 18,
        DWARFDebugInfo = 19,
        DWARFDebugLine = 20,
        DWARFDebugLoc = 21,
        DWARFDebugMacInfo = 22,
        DWARFDebugMacro = 23,
        DWARFDebugPubNames = 24,
        DWARFDebugPubTypes = 25,
        DWARFDebugRanges = 26,
        DWARFDebugStr = 27,
        DWARFDebugStrOffsets = 28,
        DWARFAppleNames = 29,
        DWARFAppleTypes = 30,
        DWARFAppleNamespaces = 31,
        DWARFAppleObjC = 32,
        ELFSymbolTable = 33,
        ELFDynamicSymbols = 34,
        ELFRelocationEntries = 35,
        ELFDynamicLinkInfo = 36,
        EHFrame = 37,
        ARMexidx = 38,
        ARMextab = 39,
        CompactUnwind = 40,
        GoSymtab = 41,
        AbsoluteAddress = 42,
        Other = 43
    }

    public enum EmulateInstructionOptions : uint
    {
        None = 0,
        AutoAdvancePC = 1,
        IgnoreConditions = 2
    }

    [Flags]
    public enum FunctionNameType : uint
    {
        None = 0,
        Auto = 2,
        Full = 4,
        Base = 8,
        Method = 16,
        Selector = 32,
        Any = 2
    }

    public enum BasicType : uint
    {
        Invalid = 0,
        Void = 1,
        Char = 2,
        SignedChar = 3,
        UnsignedChar = 4,
        WChar = 5,
        SignedWChar = 6,
        UnsignedWChar = 7,
        Char16 = 8,
        Char32 = 9,
        Short = 10,
        UnsignedShort = 11,
        Int = 12,
        UnsignedInt = 13,
        Long = 14,
        UnsignedLong = 15,
        LongLong = 16,
        UnsignedLongLong = 17,
        Int128 = 18,
        UnsignedInt128 = 19,
        Bool = 20,
        Half = 21,
        Float = 22,
        Double = 23,
        LongDouble = 24,
        FloatComplex = 25,
        DoubleComplex = 26,
        LongDoubleComplex = 27,
        ObjCID = 28,
        ObjCClass = 29,
        ObjCSel = 30,
        NullPtr = 31,
        Other = 32
    }

    public enum TypeClass : uint
    {
        Invalid = 0,
        Array = 1,
        BlockPointer = 2,
        Builtin = 4,
        Class = 8,
        ComplexFloat = 16,
        ComplexInteger = 32,
        Enumeration = 64,
        Function = 128,
        MemberPointer = 256,
        ObjCObject = 512,
        ObjCInterface = 1024,
        ObjCObjectPointer = 2048,
        Pointer = 4096,
        Reference = 8192,
        Struct = 16384,
        Typedef = 32768,
        Union = 65536,
        Vector = 131072,
        Other = 2147483648,
        Any = 0xffffffff
    }

    public enum TemplateArgumentKind : uint
    {
        Null = 0,
        Type = 1,
        Declaration = 2,
        Integral = 3,
        Template = 4,
        TemplateExpansion = 5,
        Expression = 6,
        Pack = 7
    }

    [Flags]
    public enum TypeOptions : uint
    {
        None = 0,
        Cascade = 1,
        SkipPointers = 2,
        SkipReferences = 4,
        HideChildren = 8,
        HideValue = 16,
        ShowOneLiner = 32,
        HideNames = 64,
        NonCacheable = 128,
        HideEmptyAggregates = 256
    }

    public enum FrameComparison : uint
    {
        Invalid = 0,
        Unknown = 1,
        Equal = 2,
        SameParent = 3,
        Younger = 4,
        Older = 5
    }

    public enum AddressClass : uint
    {
        Invalid = 0,
        Unknown = 1,
        Code = 2,
        CodeAlternateISA = 3,
        Data = 4,
        Debug = 5,
        Runtime = 6
    }

    public enum FilePermissions : uint
    {
        UserRead = 256,
        UserWrite = 128,
        UserExecute = 64,
        GroupRead = 32,
        GroupWrite = 16,
        GroupExecute = 8,
        WorldRead = 4,
        WorldWrite = 2,
        WorldExecute = 1,
        UserRW = 384,
        ionsUserRX = 320,
        UserRWX = 448,
        GroupRW = 48,
        GroupRX = 40,
        GroupRWX = 56,
        WorldRW = 6,
        WorldRX = 5,
        WorldRWX = 7,
        EveryoneR = 292,
        EveryoneW = 146,
        EveryoneX = 73,
        EveryoneRW = 438,
        EveryoneRX = 365,
        EveryoneRWX = 511,
        FileDefault = 384,
        DirectoryDefault = 448
    }

    public enum QueueItemKind : uint
    {
        Unknown = 0,
        Function = 1,
        Block = 2
    }

    public enum QueueKind : uint
    {
        Unknown = 0,
        Serial = 1,
        Concurrent = 2
    }

    public enum ExpressionEvaluationPhase : uint
    {
        Parse = 0,
        IRGen = 1,
        Execution = 2,
        Complete = 3
    }

    public enum WatchpointKind : uint
    {
        Read = 1,
        Write = 2
    }

    public enum GdbSignal : uint
    {
        BadAccess = 0x91,
        BadInstruction = 0x92,
        Arithmetic = 0x93,
        Emulation = 0x94,
        Software = 0x95,
        Breakpoint = 0x96
    }

    public enum PathType : uint
    {
        LLDBShlibDir = 0,
        SupportExecutableDir = 1,
        HeaderDir = 2,
        PythonDir = 3,
        LLDBSystemPlugins = 4,
        LLDBUserPlugins = 5,
        LLDBTempSystemDir = 6,
        GlobalLLDBTempSystemDir = 7,
        ClangDir = 8
    }

    public enum MemberFunctionKind : uint
    {
        Unknown = 0,
        Constructor = 1,
        Destructor = 2,
        InstanceMethod = 3,
        StaticMethod = 4
    }

    public enum MatchType : uint
    {
        Normal = 0,
        Regex = 1,
        StartsWith = 2
    }

    [Flags]
    public enum TypeFlags : uint
    {
        HasChildren = 1,
        HasValue = 2,
        IsArray = 4,
        IsBlock = 8,
        IsBuiltIn = 16,
        IsClass = 32,
        IsCPlusPlus = 64,
        IsEnumeration = 128,
        IsFuncPrototype = 256,
        IsMember = 512,
        IsObjC = 1024,
        IsPointer = 2048,
        IsReference = 4096,
        IsStructUnion = 8192,
        IsTemplate = 16384,
        IsTypedef = 32768,
        IsVector = 65536,
        IsScalar = 131072,
        IsInteger = 262144,
        IsFloat = 524288,
        IsComplex = 1048576,
        IsSigned = 2097152,
        InstanceIsPointer = 4194304
    }

    [Flags]
    public enum CommandFlags : uint
    {
        RequiresTarget = 1,
        RequiresProcess = 2,
        RequiresThread = 4,
        RequiresFrame = 8,
        RequiresRegContext = 16,
        TryTargetAPILock = 32,
        ProcessMustBeLaunched = 64,
        ProcessMustBePaused = 128
    }

    public enum TypeSummaryCapping : uint
    {
        Capped = 1,
        Uncapped = 0
    }
}
