//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace LLDB
{
    public unsafe partial class Event : IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 12)]
        public partial struct Internal
        {
            [FieldOffset(8)]
            public global::System.IntPtr m_opaque_ptr;

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZN4lldb7SBEventC2Ev")]
            internal static extern void ctor_0(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZN4lldb7SBEventC2ERKS0_")]
            internal static extern void cctor_1(global::System.IntPtr instance, global::System.IntPtr rhs);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZN4lldb7SBEventC2EjPKcj")]
            internal static extern void ctor_2(global::System.IntPtr instance, uint @event, global::System.IntPtr cstr, uint cstr_len);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZN4lldb7SBEventD2Ev")]
            internal static extern void dtor_0(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZNK4lldb7SBEvent7IsValidEv")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool IsValid_0(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZNK4lldb7SBEvent14GetBroadcasterEv")]
            internal static extern void GetBroadcaster_0(global::System.IntPtr @return, global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZN4lldb7SBEvent21BroadcasterMatchesPtrEPKNS_13SBBroadcasterE")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool BroadcasterMatchesPtr_0(global::System.IntPtr instance, global::System.IntPtr broadcaster);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZN4lldb7SBEvent21BroadcasterMatchesRefERKNS_13SBBroadcasterE")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool BroadcasterMatchesRef_0(global::System.IntPtr instance, global::System.IntPtr broadcaster);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZN4lldb7SBEvent5ClearEv")]
            internal static extern void Clear_0(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZN4lldb7SBEvent19GetCStringFromEventERKS0_")]
            internal static extern global::System.IntPtr GetCStringFromEvent_0(global::System.IntPtr @event);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZN4lldb7SBEvent14GetDescriptionERNS_8SBStreamE")]
            [return: MarshalAsAttribute(UnmanagedType.I1)]
            internal static extern bool GetDescription_0(global::System.IntPtr instance, global::System.IntPtr description);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZN4lldb7SBEvent13GetDataFlavorEv")]
            internal static extern global::System.IntPtr GetDataFlavor_0(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZNK4lldb7SBEvent7GetTypeEv")]
            internal static extern uint GetType_0(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("lldb", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="_ZNK4lldb7SBEvent19GetBroadcasterClassEv")]
            internal static extern global::System.IntPtr GetBroadcasterClass_0(global::System.IntPtr instance);
        }

        public global::System.IntPtr __Instance { get; protected set; }
        public static readonly System.Collections.Concurrent.ConcurrentDictionary<IntPtr, Event> NativeToManagedMap = new System.Collections.Concurrent.ConcurrentDictionary<IntPtr, Event>();

        private readonly bool __ownsNativeInstance;

        public static Event __CreateInstance(global::System.IntPtr native)
        {
            return new Event((Event.Internal*) native);
        }

        public static Event __CreateInstance(Event.Internal native)
        {
            return new Event(native);
        }

        private static Event.Internal* __CopyValue(Event.Internal native)
        {
            var ret = (Event.Internal*) Marshal.AllocHGlobal(12);
            *ret = native;
            return ret;
        }

        private Event(Event.Internal native)
            : this(__CopyValue(native))
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected Event(Event.Internal* native, bool isInternalImpl = false)
        {
            __Instance = new global::System.IntPtr(native);
        }

        public Event()
        {
            __Instance = Marshal.AllocHGlobal(12);
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            Internal.ctor_0(__Instance);
        }

        public Event(uint @event, string cstr, uint cstr_len)
        {
            __Instance = Marshal.AllocHGlobal(12);
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            var arg0 = @event;
            var arg1 = Marshal.StringToHGlobalAnsi(cstr);
            var arg2 = cstr_len;
            Internal.ctor_2(__Instance, arg0, arg1, arg2);
            Marshal.FreeHGlobal(arg1);
        }

        public void Dispose()
        {
            Dispose(disposing: true);
        }

        protected virtual void Dispose(bool disposing)
        {
            DestroyNativeInstance(false);
        }

        public virtual void DestroyNativeInstance()
        {
            DestroyNativeInstance(true);
        }

        private void DestroyNativeInstance(bool force)
        {
            LLDB.Event __dummy;
            NativeToManagedMap.TryRemove(__Instance, out __dummy);
            if (__ownsNativeInstance || force)
                Internal.dtor_0(__Instance);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
        }

        public bool IsValid()
        {
            var __ret = Internal.IsValid_0(__Instance);
            return __ret;
        }

        public LLDB.Broadcaster GetBroadcaster()
        {
            var __ret = new LLDB.Broadcaster.Internal();
            Internal.GetBroadcaster_0(new IntPtr(&__ret), __Instance);
            return LLDB.Broadcaster.__CreateInstance(__ret);
        }

        public bool BroadcasterMatchesPtr(LLDB.Broadcaster broadcaster)
        {
            var arg0 = ReferenceEquals(broadcaster, null) ? global::System.IntPtr.Zero : broadcaster.__Instance;
            var __ret = Internal.BroadcasterMatchesPtr_0(__Instance, arg0);
            return __ret;
        }

        public bool BroadcasterMatchesRef(LLDB.Broadcaster broadcaster)
        {
            var arg0 = ReferenceEquals(broadcaster, null) ? global::System.IntPtr.Zero : broadcaster.__Instance;
            var __ret = Internal.BroadcasterMatchesRef_0(__Instance, arg0);
            return __ret;
        }

        public void Clear()
        {
            Internal.Clear_0(__Instance);
        }

        public bool GetDescription(LLDB.Stream description)
        {
            var arg0 = ReferenceEquals(description, null) ? global::System.IntPtr.Zero : description.__Instance;
            var __ret = Internal.GetDescription_0(__Instance, arg0);
            return __ret;
        }

        public static string GetCStringFromEvent(LLDB.Event @event)
        {
            var arg0 = ReferenceEquals(@event, null) ? global::System.IntPtr.Zero : @event.__Instance;
            var __ret = Internal.GetCStringFromEvent_0(arg0);
            return Marshal.PtrToStringAnsi(__ret);
        }

        public string DataFlavor
        {
            get
            {
                var __ret = Internal.GetDataFlavor_0(__Instance);
                return Marshal.PtrToStringAnsi(__ret);
            }
        }

        public uint Type
        {
            get
            {
                var __ret = Internal.GetType_0(__Instance);
                return __ret;
            }
        }

        public string BroadcasterClass
        {
            get
            {
                var __ret = Internal.GetBroadcasterClass_0(__Instance);
                return Marshal.PtrToStringAnsi(__ret);
            }
        }
    }
}
